In [12]:
# stu_a, stu_b 독립적으로 존재
stu_a = Student() # 클래스로부터 인스턴스 초기화
stu_b = Student() # 클래스로부터 인스턴스 초기화

In [14]:
stu_a.greeting()

안녕하세요.


In [15]:
stu_b.greeting()

안녕하세요.


In [ ]:
stu_a.hello = "안녕하세요."

In [6]:
stu_a.name = '학생A'

In [7]:
print(stu_a.name)

학생A


In [4]:
print(stu_a.hello)

안녕하세요.


In [5]:
print(stu_b.hello)

AttributeError: 'Student' object has no attribute 'hello'

In [19]:
class Person:
    def __init__(self,name,age):
        self.name = name
        self.age = age

In [17]:
p1 = Person("name1",32)
p2 = Person("name2",40)

In [20]:
p1.__dict__

{'name': 'name1', 'age': 40}

In [21]:
p2.__dict__

{'name': 'name2', 'age': 32}

In [18]:
# p1.name = "name1"
# p1.age = 40

# p2.name = "name2"
# p2.age = 32

In [24]:
class Person:
    def __init__(self, name, age, address):
        self.hello = "안녕하세요."
        self.name = name
        self.age = age
        self.address = address
        
    def greeting(self):
        print(f"{self.hello} 제 이름은 {self.name}입니다.")
        
maria = Person("마리아",20,"서울시 서초구 반포동")
maria.greeting()

print("이름:", maria.name)
print("나이:", maria.age)
print("주소:", maria.address)

안녕하세요. 제 이름은 마리아입니다.
이름: 마리아
나이: 20
주소: 서울시 서초구 반포동


In [58]:
i = 0
name = []
age = []
address = []

while i < 2 :
    i +=1
    name = input("이름은 무엇인가요?")
    age = input("나이는 무엇인가요?")
    address = input("주소는 무엇인가요?")


class Person2:
    def __init__(self,name,age,address):
        self.name = name
        self.age = age
        self.address = address

        
    def greeting(self):
        print(f"첫번쨰 이름 : {self.name}")
        print(f"첫번쨰 나이 : {self.age}")
        print(f"첫번쨰 주소 : {self.address}")

maria = Person2(name,age,address)
maria.greeting()

james = Person2(name,age,address)
james.greeting()

이름은 무엇인가요? 홍길동
나이는 무엇인가요? 20
주소는 무엇인가요? 주소
이름은 무엇인가요? 홍길동2
나이는 무엇인가요? 30
주소는 무엇인가요? 주소


첫번쨰 이름 : 홍
첫번쨰 나이 : 3
첫번쨰 주소 : 주
첫번쨰 이름 : 홍
첫번쨰 나이 : 3
첫번쨰 주소 : 주


In [62]:
class Person():
    abc = "abc"
    def __init__(self,name,age,address) : #생성자
        self.hello = '안녕하세요. 저는 사람입니다.'
        self.name= name
        self.age = age
        self.address = address
    
    def greeting(self):
        print("{0} 저는 {1}입니다.".format(self.hello,self.name))
        
name = input("이름은 무엇인가요?:")
age = input("나이는 무엇인가요?:")
address = input("주소는 무엇인가요?:")
maria = Person(name,age,address)

name = input("이름은 무엇인가요?:")
age = input("나이는 무엇인가요?:")
address = input("주소는 무엇인가요?:")
james = Person(name,age,address)

print(f"첫번쨰 이름:{maria.name}")
print(f"첫번쨰 이름:{maria.age}")
print(f"첫번쨰 이름:{maria.address}")

print(f"두번쨰 이름:{james.name}")
print(f"두번쨰 이름:{james.age}")
print(f"두번쨰 이름:{james.address}")


이름은 무엇인가요?: 홍길동
나이는 무엇인가요?: 20
주소는 무엇인가요?: 주소
이름은 무엇인가요?: 홍길동3
나이는 무엇인가요?: 주소
주소는 무엇인가요?: 20


첫번쨰 이름:홍길동
첫번쨰 이름:20
첫번쨰 이름:주소
두번쨰 이름:홍길동3
두번쨰 이름:주소
두번쨰 이름:20


In [64]:
class Person():
    abc = "abc"
    def __init__(self,name,age,address) : #생성자
        self.hello = '안녕하세요. 저는 사람입니다.'
        self.name= name
        self.age = age
        self.address = address
    
    def greeting(self):
        print("{0} 저는 {1}입니다.".format(self.hello,self.name))
        
    def maria(self):
        name = input("이름은 무엇인가요?:")
        age = input("나이는 무엇인가요?:")
        address = input("주소는 무엇인가요?:")
        maria = Person(name,age,address)
        
    def james(self):
        name = input("이름은 무엇인가요?:")
        age = input("나이는 무엇인가요?:")
        address = input("주소는 무엇인가요?:")
        james = Person(name,age,address)
        
        

print(f"첫번쨰 이름:{maria.name}")
print(f"첫번쨰 이름:{maria.age}")
print(f"첫번쨰 이름:{maria.address}")

print(f"두번쨰 이름:{james.name}")
print(f"두번쨰 이름:{james.age}")
print(f"두번쨰 이름:{james.address}")


첫번쨰 이름:홍길동
첫번쨰 이름:20
첫번쨰 이름:주소
두번쨰 이름:홍길동3
두번쨰 이름:주소
두번쨰 이름:20


### 비공개 속성 사용하기
- 우리가 인스턴스.속성 = 값을 통해 새롭게 인스턴스의 속성 값을 변경 못하도록 막고 싶을 때는 비공개 속성을 사용

- 사용법은 해당하는 속성 앞에 던더(__)를 붙이면 비공개 속성이 됨

In [76]:
class Person3:
    def __init__(self, name, age, address, wallet):
        self.hello = "안녕하세요."
        self.name = name
        self.age = age
        self.address = address
        self.__wallet = wallet
        
    def greeting(self):
        print(f"{self.hello} 제 이름은 {self.name}입니다.")
        
    def amount(self):
        print(self.__wallet)

In [77]:
lks = Person3("이기수",55,"경기도 시흥",500)

In [78]:
lks.amount()

500


In [69]:
print(lks.name)

이기수


In [70]:
print(lks.age)

55


In [72]:
print(lks.address)

경기도 시흥


In [73]:
print(lks.wallet)

AttributeError: 'Person3' object has no attribute 'wallet'

In [81]:
class Person3 : 
    def __init__(self,name,age,address,wallet):
        self.name = name
        self.age = age
        self.address = address
        self.__wallet = wallet # 변수 앞에 _를 붙여서 비공개 속성으로)
        
    def pay(self,amount):
        if self.__wallet < amount:
            print("돈이 모자랍니다.")
            return
        self.__wallet -= amount # 비공개 속성은 클래스 안의 메서드에서 접근할 수 있음

IndentationError: unexpected indent (3519910880.py, line 13)

In [98]:
class Annie :
    def __init__(self,health,mana,ability_power):
        self.health = health
        self.mana = mana
        self.ability_power = ability_power
        
    def tibbers(self):
        print(f"티버: 피해량 {self.ability_power * 0.65 + 400}")
        
health,mana,ability_power = map(float,input("체력, 마나, AP를 입력하세요").split())


i = Annie(health = health , mana = mana,ability_power = ability_power)
i.tibbers()

체력, 마나, AP를 입력하세요 1803.68 1184.0 645


티버: 피해량 819.25


In [97]:
class Annie:
    def __init__(self, health, mana, ability_power):
        self.helath = health
        self.mana = mana
        self.ability_power = ability_power
    def tibbers(self):
        print(f"티버: 피해량{self.ability_power * 0.65 + 400}")
        
health,mana,ability_power = map(float,input("체력,마나,AP를 입력하세요.").split())

x = Annie(health=health, mana=mana, ability_power = ability_power)
x.tibbers()

체력,마나,AP를 입력하세요. 1803.68 1184.0 645


티버: 피해량819.25


In [103]:
!conda list

# packages in environment at C:\Users\Playdata\anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0            py39haa95532_0  
alabaster                 0.7.12             pyhd3eb1b0_0  
anaconda                  2022.10                  py39_0  
anaconda-client           1.11.0           py39haa95532_0  
anaconda-navigator        2.3.1            py39haa95532_0  
anaconda-project          0.11.1           py39haa95532_0  
anyio                     3.5.0            py39haa95532_0  
appdirs                   1.4.4              pyhd3eb1b0_0  
argon2-cffi               21.3.0             pyhd3eb1b0_0  
argon2-cffi-bindings      21.2.0           py39h2bbff1b_0  
arrow                     1.2.2              pyhd3eb1b0_0  
astroid                   2.11.7           py39haa95532_0  
astropy                   5.1              py39h080aedc_0  
atomicwrites              1.4.0                      py_0  
attrs                     21.4.0 

In [99]:
import numpy as np

In [102]:
ar = np.array([_ for _ in range(10)])
ar
ar.shape ##넘파이 배열의 모양을 확인

(10,)

In [104]:
type(ar)

numpy.ndarray

In [105]:
ar2 = np.array([0.1, 5,4,12,0.5])
ar2

array([ 0.1,  5. ,  4. , 12. ,  0.5])

In [106]:
x = np.array([1,2,3])
x.dtype

dtype('int32')

In [107]:
x = np.array([1.0,2.0,3.0])
x.dtype

dtype('float64')

In [108]:
# 01010101 -> 8bits == 1byte

In [115]:
ar3 = np.array([_ for _ in range(3,10,3)], 'i8') #int8bytes --> 8*8bit
print(ar3)
print(ar3.dtype)

[3 6 9]
int64


In [113]:
ar4 = np.array([_ for _ in range(2,10,2)], 'f8')
print(ar4)
print(ar4.dtype)

[2. 4. 6. 8.]
float64


In [118]:
# 'U8' 유니코드 8글자 자료형을 명시적으로 선언
# 그래서 시퀀스 자료형 중 제일 큰 값이 <U5이지만 <u8로 타입이 지정되었다.
ar5 = np.array(["까나다라마","바사아","자","차카"], 'U8')
print(ar5)
print(ar5.dtype)
# <U8은 최대 8글자의 유니코드 자료형이다.

['까나다라마' '바사아' '자' '차카']
<U8


In [120]:
# 넘파이의 자료형
# 첫 번쨰 넘파이 배열에서 'f'를 활용하여 float로 dtype을 지정해줬습니다. 
# dtype 속성을 활용해 타입을 확인하니 32비트의 float형으로 생성된 것을 확인할 수 있습니다.
# 이 타입간 덧셈 연산(+)의 결과는 숫자로 계산됨을 확인할 수 있습니다.
# 바로 아래 넘파이 배열에서는 유니코드 문자열을 타입으로 지정해서 생성하였습니다.
# 1글자 이하의 글자들로 구성된 유니코드임을 추가적으로 설명하고 있습니다.
# 유니코드 간 덧셈 연산(+)은 concatenate의 결과를 보여줍니다.

x = np.array([1,2,3],dtype='f')
x.dtype

x[0] + x[1]

3.0

In [121]:
# 넘파이의 자료형
# 넘파이에서는 무한대를 표현하기 위한 np.inf(infinity)와 정의할 수 없는 숫자를 나타내는 np.nan(not a number)을 사용할 수 있습니다.
# 다음 예와 같이 1을 0으로 나누려고 하거나 0에 대한 로그 값을 계산하면 무한대인 np.inf이 나옵니다. 0을 0으로 나누려고 시도하면 np.nan이 나옵니다

np.array([0,1,-1,0]) / np.array([1,0,0,0])

C:\Users\Playdata\AppData\Local\Temp\ipykernel_18620\1001721884.py:5: RuntimeWarning: divide by zero encountered in true_divide
  np.array([0,1,-1,0]) / np.array([1,0,0,0])
C:\Users\Playdata\AppData\Local\Temp\ipykernel_18620\1001721884.py:5: RuntimeWarning: invalid value encountered in true_divide
  np.array([0,1,-1,0]) / np.array([1,0,0,0])


array([  0.,  inf, -inf,  nan])

In [122]:
np.exp(-np.inf)

0.0

In [123]:
# 백터화 연산(Vectorized Operation)
# 넘파이 배열 객체는 배열의 각 요소에 대한 반복 연산을 하나의 명령어로 처리하는 백터화 연산(vectorized operation)을 지원합니다.
# 예를 들어 다음처럼 리스트 내 모든 요소 데이터를 모두 2배 해야 하는 경우를 생각해봅시다.

data = [0,1,2,3,4,5,6,7,8,9]
answer = [2*d for d in data]
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [125]:
# 넘파이 배열 객체의 벡터화 연산을 사용하면 다음과 같이 for 반복문이 없이 간단하게 단 한번의 연산식으로 표현할 수 있습니다.
# 물론 계산 속도도 리스트 객체에 반복문을 사용해서 처리하는 것보다 훨씬 빠릅니다.

x = np.array(data)
x
2* x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [127]:
# 백터화 연산(Vectorized Operation)
# 앞서 학습했던 내용으로 파이썬 리스트 객체에 정수를 곱하면(*) 객체의 크기가 곱한 숫자만큼 반복 증가합니다.
# 넘파이 배열 객체는 벡터화 연산이 이뤄진다고 바로 앞에서 설명 드렸습니다.
# 이 차이점을 분명히 기억해둬야 합니다.
# 백터화 연산은 비교 연산과 논리 연산을 포함한 모든 종류의 수학 연산에 대해 적용됩니다.

a = np.array([1,2,3])
b = np.array([10,20,30])

2 * a+b

array([12, 24, 36])

In [128]:
a ==2

array([False,  True, False])

In [129]:
b > 10

array([False,  True,  True])

In [130]:
(a ==2) & (b > 10)

array([False,  True, False])

In [136]:
# 2차원 배열 만들기
# 2차원 배열은 수학에서 행렬(matrix)이라고 했었습니다.
# 행렬에서는 가로줄을 행(row)이라고 하고 세로줄은(column)이라고 합니다.
# 다음과 같이 리스트를 중첩하여 리스트의 리스트(list of list)를 이용해서 2차원 배열처럼 생성할 수 있습니다.
# 안쪽 리스트의 길이는 행렬의 열의 수 즉 가로 크기가 되고, 바깥쪽 리스트의 길이는 행의 수, 즉 세로 크기가 됩니다.

c = np.array([[0,1,2],
              [3,4,5]])

In [137]:
c

array([[0, 1, 2],
       [3, 4, 5]])

In [138]:
c.shape

(2, 3)

In [139]:
# 행의 갯수
len(c)

2

In [140]:
# 행의 열의 갯수
len(c[0])

3

In [142]:
x = np.array([[10,20,30,40],
              [50,60,70,80]])

print(x)

[[10 20 30 40]
 [50 60 70 80]]


In [146]:
# 3차원 배열 만들기
# 3차원 배열의 구조는 '깊이 x 행 x 열'의 모양을 갖습니다.

# 2 x 3 x 4
d = np.array([[[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]],
              [[11,12,13,14],
               [15,16,17,18],
               [19,250,21,22]]])
d

array([[[  1,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]],

       [[ 11,  12,  13,  14],
        [ 15,  16,  17,  18],
        [ 19, 250,  21,  22]]])

In [147]:
len(d),len(d[0]),len(d[0][0])

(2, 3, 4)

In [148]:
d.shape

(2, 3, 4)

In [149]:
# 배열의 차원과 크기 알아내기
# 배열의 차원 및 크기를 구하는 더 간단한 방법은 배열의 ndim 속성과 shape 속성을 이용하는것
# ndim 속성은 배열의 차원, shape 속성은 배열의 크기 반환

# a=np.array([1,2,3])
print(a.ndim)
print(a.shape)

1
(3,)


In [150]:
# c =np.array([0,1,2],[3,4,5])
print(c.ndim)
print(c.shape)

print(d.ndim)
print(d.shape)

2
(2, 3)
3
(2, 3, 4)


In [151]:
a = np.array([0,1,2,3,4])

In [152]:
a[1]

1

In [153]:
a[-1]

4

In [154]:
# 배열의 인덱싱
# 다차원 배열일 떄는 다음과 같이 콤마(comma , )를 사용하여 접근할 수 있습니다.
# 콤마로 구분된 차원을 축(axis)이라고도 합니다. 그래프의 x축과 y축을 떠올리면 됩니다.

a = np.array([[0,1,2],[3,4,5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [155]:
a[0,0] # 첫번쨰 행의 첫번쨰 열

0

In [156]:
# 배열의 슬라이싱
# 배열 객체로 구현한 다차원 배열의 원소 중 복수 개를 접근하려면 일반적인 파이썬 슬라이싱(slicing)과 comma(,)를 함꼐 사용하면 됨

a = np.array([[0,1,2,3],[4,5,6,7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [157]:
a[0,:] # 첫번쨰 행 전체

array([0, 1, 2, 3])

In [158]:
a[:,1] # 두번쨰 열 전체

array([1, 5])

In [159]:
a[1,1:] # 두번째 행의 두번쨰 열부터 끝열까지

array([5, 6, 7])

In [160]:
a[:2,:2]

array([[0, 1],
       [4, 5]])

In [161]:
np.array([_ for _ in range(8)]).reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [163]:
 m = np.array([_ for _ in range(15)]).reshape(3,5)

In [164]:
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [183]:
m[1,2]

7

In [185]:
m[2,-1]

14

In [188]:
m[1,1:3]

array([6, 7])

In [204]:
m[1:,2]

array([ 7, 12])

In [226]:
m[:2,-2:]

array([[3, 4],
       [8, 9]])

In [227]:
# 배열 생성
# arange 명령은 Numpy 버전의 range 명령
# 특정한 규칙에 따라 증가하는 수열을 만듬

np.arange(10) # 0 .. n-1

np.arange(3,21,2) # 시작, 끝(포함하지 않음), 단계

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [228]:
# 배열 생성
# linspace 명령이나 logspace 명령은 선형 구간 혹은 로그 구간을 지정한 구간의 수만큼 분할

np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [229]:
ex = np.linspace(0,100,20)
ex

array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ])

In [230]:
ex2 = np.logspace(0,100,5)
ex2

array([1.e+000, 1.e+025, 1.e+050, 1.e+075, 1.e+100])

In [231]:
# 전치 연산
# 2차원 배열의 전치(transpose) 연산은 행과 열을 바꾸는 작업입니다.
# 이는 배열의 T속성으로 구할 수 있습니다. 메서드가 아닌 속성이라는 점에 유의합니다.

A = np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [232]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [234]:
# 배열의 크기 변형
# 만들어진 배열의 내부 데이터는 보존한 채로 형태만 바꾸려면 reshape 명령이나 메서드 사용

ex3 = np.arange(12)
ex3.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [235]:
# 배열의 크기 변형
# 사용하는 원소의 개수가 정해져 있기 떄문에 

In [237]:
# 다차원 배열은 1차원으로 만들기 위해서는 flatten 혹은 ravel 메서드를 사용
a.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [238]:
a.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])

In [241]:
# 배열 연결
# vstack 명령은 열의 수가 같은 두 개 이상의 배열을

b1 = np.ones((2,3))
b2 = np.zeros((3,3))
print(b1)
print(b2)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [240]:
np.vstack([b1,b2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [242]:
y = np.arange(10,160,10)

In [243]:
print(y)

[ 10  20  30  40  50  60  70  80  90 100 110 120 130 140 150]


In [246]:
e = np.zeros((3,3))
d = np.ones((3,2))

print(e)
print(d)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [278]:
y = np.hstack([e,d])
print(y)

[[0. 0. 0. 1. 1.]
 [0. 0. 0. 1. 1.]
 [0. 0. 0. 1. 1.]]


In [285]:
t= np.array([_ for _ in range(10,151,10)]).reshape(3,5)

print(t)

i = np.vstack([y,t])
print(i)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]
 [110 120 130 140 150]]
[[  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [  0.   0.   0.   1.   1.]
 [ 10.  20.  30.  40.  50.]
 [ 60.  70.  80.  90. 100.]
 [110. 120. 130. 140. 150.]]


In [274]:
i = np.array([[y],[t]])

In [275]:
print(i)

[[[[  0.   0.   0.   1.   1.]
   [  0.   0.   0.   1.   1.]
   [  0.   0.   0.   1.   1.]]]


 [[[ 10.  20.  30.  40.  50.]
   [ 60.  70.  80.  90. 100.]
   [110. 120. 130. 140. 150.]]]]
