In [3]:
import numpy as np
practice = np.array([[1.1, 7.1, 8.0, 2.1, 6.5, 7.2],
                     [2.7, 5.2, 3.3, 9.0, 7.7, 2.8],
                     [0.7, 8.8, 4.2, 8.9, 4.3, 7.4],
                     [8.2, 1.1, 5.4, 2.9, 6.9, 0.2],
                     [7.4, 4.8, 2.7, 3.1, 2.8, 8.9]])

In [10]:
# 전체의 최댓값
print(practice.max())

# 각 행의 합
print(practice.sum(axis=0))

# 각 행의 최댓값
print(practice.max(axis=0))

# 각 열의 평균
print(practice.mean(axis=1))

# 각 열의 최솟값
print(practice.min(axis=1))

9.0
[20.1 27.  23.6 26.  28.2 26.5]
[8.2 8.8 8.  9.  7.7 8.9]
[5.33333333 5.11666667 5.71666667 4.11666667 4.95      ]
[1.1 2.7 0.7 0.2 2.7]


In [12]:
a = np.array([[4,3,5,7],
              [1,12,11,9],
              [2,15,1,14]])

a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [13]:
np.sort(a) # axis=-1 또는 axis=1과 동일

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [14]:
np.sort(a, axis=0)

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [15]:
a.sort(axis=1)
a

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [16]:
# 자료 정렬 argsort
a = np.array([42,38,12,25])
j = np.argsort(a)
j

array([2, 3, 1, 0], dtype=int64)

In [17]:
a[j]

array([12, 25, 38, 42])

In [18]:
np.sort(a)

array([12, 25, 38, 42])

In [19]:
# 고급 인덱싱 - 인덱스 배열을 사용한 인덱싱

a= np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [20]:
print(a[[0,1,2],[0,1,0]]) #a[0,0] a[1,1] a[2,0]을 인덱스로 하는 1차원 배열(shape=3,))을 출력해준다.

[1 4 5]


In [21]:
# 슬라이싱 범위
print(a[:,[0,1,0]])

[[1 2 1]
 [3 4 3]
 [5 6 5]]


In [23]:
# 연습문제

scores = np.array([[1,2,3,4],
                   [46,99,100,71],
                   [81,59,90,100]])

scores

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [38]:
i = np.argsort(scores[1,:])
i

array([0, 3, 1, 2], dtype=int64)

In [40]:
print(scores[:,[0,3,1,2]])

[[  1   4   2   3]
 [ 46  71  99 100]
 [ 81 100  59  90]]


In [39]:
print(scores[:,i])

[[  1   4   2   3]
 [ 46  71  99 100]
 [ 81 100  59  90]]


In [41]:
# 시드 설정하기
np.random.seed(0)

In [42]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [43]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [44]:
np.random.rand(10)

array([0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443])

In [45]:
np.random.seed(0)

In [46]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [47]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [48]:
np.random.rand(10)

array([0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443])

In [49]:
# shuffle

x= np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
np.random.shuffle(x)
x

array([3, 6, 4, 5, 2, 9, 7, 8, 1, 0])

In [52]:
# 아래의 코드에서는 np.random.choice()의 첫 인수를 정수 5로 전달하며 np.arange(5)의 결과를 만듬

np.random.choice(5,5,replace=False) # shuffle 명령과 같다.

array([1, 4, 0, 3, 2])

In [53]:
np.random.choice(5,3,replace=False) #3개만 선택

array([2, 1, 3])

In [54]:
np.random.choice(5,10) #반복해서 10개 선택

array([0, 4, 1, 4, 1, 2, 2, 0, 1, 1])

In [55]:
np.random.choice(5,10,p=[0.1,0,0.3,0.6,0]) # 선택 확률을 다르게 해서 10개 선택

array([0, 3, 3, 2, 2, 3, 3, 2, 0, 3])

In [56]:
# 난수 생성
np.random.randn(10)

array([ 0.11495917,  0.34531264, -1.73495876,  1.65835111,  2.29977152,
       -0.47113526,  1.26271548, -1.17051545,  1.0657892 , -0.69993739])

In [57]:
np.random.randn(3,5)

array([[ 0.14407911,  0.3985421 ,  0.02686925,  1.05583713, -0.07318342],
       [-0.66572066, -0.04411241, -0.36326702, -0.01234481,  0.04212149],
       [ 1.95929589, -0.1984257 ,  0.33053441, -1.43582841,  0.02752832]])

In [58]:
np.random.randint(10)

9

In [59]:
np.random.randint(10,20,size=10)

array([11, 14, 16, 18, 12, 13, 10, 10, 16, 10])

In [120]:
np.random.seed(0)

In [101]:
a = np.random.randint(0,2,size=100)
a

array([0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0])

In [110]:
a.sum() /len(a)

0.56

In [121]:
# 주사위는 1부터 6까지의 숫자를 가집니다. 이 주사위를 100번 던져서 나오는 숫자를 넘파이 난수를 발생시켜 시뮬레이션하고 나오는 숫자의 평균을 구해보세요.(seed는 0으로 설정)
t = np.random.randint(1,7,100)
t

array([5, 6, 1, 4, 4, 4, 2, 4, 6, 3, 5, 1, 1, 5, 3, 2, 1, 2, 6, 2, 6, 1,
       2, 5, 4, 1, 4, 6, 1, 3, 4, 1, 2, 4, 6, 4, 4, 1, 2, 2, 2, 1, 3, 5,
       4, 4, 3, 5, 3, 1, 1, 5, 6, 6, 1, 5, 2, 5, 2, 3, 3, 1, 2, 2, 2, 2,
       4, 4, 3, 4, 1, 4, 6, 5, 2, 3, 5, 4, 5, 5, 5, 4, 5, 5, 5, 1, 5, 4,
       3, 6, 6, 6, 1, 2, 6, 2, 4, 1, 6, 1])

In [122]:
np.mean(t)

3.42

In [123]:
# 정수 데이터 카운팅

np.unique([11,11,2,2,34,34])

array([ 2, 11, 34])

In [124]:
a = np.array(['a','b','b','c','a'])
index,count = np.unique(a,return_counts=True)

In [125]:
index

array(['a', 'b', 'c'], dtype='<U1')

In [126]:
count

array([2, 2, 1], dtype=int64)

In [127]:
np.bincount([1,1,2,2,2,3],minlength=6)

array([0, 2, 3, 1, 0, 0], dtype=int64)