In [96]:
class Calculater():
    def __init__(self,value):
        self.value = 0
                    
    def add(self,*args) :
        for args in args:
            self.value += args
        
    def minus(self,*args) :
        for args in args:
            self.value -= args
    
    def show_value(self):
        print(f"현재 값은 {self.value}입니다.")
    

In [100]:
c= Calculater()

TypeError: __init__() missing 1 required positional argument: 'value'

In [98]:
c.add(100)
c.minus(20)
c.show_value()

현재 값은 80입니다.


In [105]:
import numpy as np

class Calculater:
    def __init__(self):
        self.value = 0
        
    def add(self, *number):
        if len(number) > 0:
            num = np.array(number)
            self.value += np.sum(num)
        else :
            print("숫자를 입력하세요.")
            
    def minus(self, *number):
        if len(number) > 0 :
            num = np.array(number)
            self.value -= np.sum(num)
        else :
            print("숫자를 입력해주세요.")
            
    def show_value(self):
        print(f'현재 값은 {self.value}입니다.')

In [106]:
c=Calculater()

In [107]:
c.add([10,20])

In [108]:
c.show_value()

현재 값은 30입니다.


In [109]:
# 브로드캐스팅
# 확장 가능한 경우를 확인하는 규칙은 다음과 가틉니다
# 1. 넘파이 배열의 shape을 우측 정렬하고 각 차원별로 숫자를 비교
# 비교하는 모든 차원이 두 조건 중 하나에 충족되어야 브로드캐스팅 가능
# a. 해당 차원 간의 숫자가 동일한 경우
# b. 해당 차원 중 하나가 1인 경우

In [110]:
# 차원 축소 연산

# 넘파이에서 지원되는 차원 축소 연산 명령 혹은 메서드
# 최대  / 최소 : min. max, argmin, argmax
# 통계 : sum,mean,median,std,var
# 불리언 : all, any

# -행렬의 하나의 행에 있는 원소들을 하나의 데이터 집합으로 보고 그 집합의 평균을 구하면 각 행에 대해 하나의 숫자가 나오게 됩니다.
# ex) 예를 들어 10 x 5 크기의 2차원 배열에 대해 행-평균을 구하면 10개의 숫자를 가진 1차원 벡터가 나오게 됩니다. 이러한 연산을 차원 축소(dimension reduction) 연산이라고 합니다.

In [111]:
# sum()
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [112]:
np.sum(x)

10

In [117]:
x.sum()

66

In [114]:
x = np.arange(12).reshape(3,-1)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [115]:
x.sum(axis=0) # axis=0은 행 간의 연산 결과를 구한다

array([12, 15, 18, 21])

In [116]:
x.sum(axis=1) # axis=1은 열 간의 연산 결과를 구한다.

array([ 6, 22, 38])

In [118]:
# min()

x = np.arange(20).reshape(2,5,-1)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [119]:
x.min()

0

In [120]:
np.min(x)

0

In [121]:
x.min(axis=0)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [122]:
np.min(x,axis=1)

array([[ 0,  1],
       [10, 11]])

In [123]:
x.min(axis=2)

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [124]:
hasattr(range,"__iter__") # 이 True이면 iterable이라는 의미

True

In [125]:
sum(range(10))

45

In [126]:
# argmin()

x = np.arange(20).reshape(2,5,-1)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [127]:
x.argmin()

0

In [128]:
np.min(x)

0

In [129]:
x.min(axis=0)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [130]:
np.argmin(x,axis=1)

array([[0, 0],
       [0, 0]], dtype=int64)

In [131]:
x.argmin(axis=2)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int64)

In [132]:
# max()

x = np.arange(20).reshape(2,5,-1)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [133]:
x.max()

19

In [134]:
np.max(x)

19

In [135]:
x.max(axis=0)

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [136]:
np.max(x,axis=1)

array([[ 8,  9],
       [18, 19]])

In [137]:
x.max(axis=2)

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19]])

In [138]:
# argmax()

x = np.arange(20).reshape(2,5,-1)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [139]:
x.argmax()

19

In [140]:
np.argmax(x)

19

In [141]:
x.argmax(axis=0)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int64)

In [142]:
np.argmax(x, axis=1)

array([[4, 4],
       [4, 4]], dtype=int64)

In [143]:
x.argmax(axis=2)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int64)

In [146]:
# np.any() , np.all()

a = np.zeros((100,100), dtype=np.int64) # 100x100 2차원 배열
a

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [147]:
practice = np.array([[1.1, 7.1, 8.0, 2.1, 6.5, 7.2],
                     [2.7, 5.2, 3.3, 9.0, 7.7, 2.8],
                     [0.7, 8.8, 4.2, 8.9, 4.3, 7.4],
                     [8.2, 1.1, 5.4, 2.9, 6.9, 0.2],
                     [7.4, 4.8, 2.7, 3.1, 2.8, 8.9]])

9.0
151.4
[8.  9.  8.9 8.2 8.9]
5.046666666666667


AxisError: axis 2 is out of bounds for array of dimension 2